CREATE TABLE IMAGE
(
    ID          INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    IMAGE       BYTEA,
    NAME        text,
    DESCRIPTION text,
    DATE_       date,
    AUTHOR      text
);

CREATE TABLE TAG
(
    ID   INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME text
);

CREATE TABLE IMAGES_TAGS
(
    IMAGE_ID INT NOT NULL,
    TAG_ID   INT NOT NULL,
    PRIMARY KEY (IMAGE_ID, TAG_ID),

    CONSTRAINT FK_IMAGE
        FOREIGN KEY (IMAGE_ID)
            REFERENCES IMAGE (ID) on delete cascade,
    CONSTRAINT FK_TAG
        FOREIGN KEY (TAG_ID)
            REFERENCES TAG (ID) on delete cascade
);