CREATE TABLE IMAGE
(
    ID          INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    IMAGE_BLOB  BYTEA,
    NAME        TEXT CHECK (NAME != ''),
    DESCRIPTION TEXT,
    DATE        DATE,
    AUTHOR_ID   INT
);

CREATE TABLE AUTHOR
(
    ID          INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    AUTHOR_NAME TEXT UNIQUE
);

CREATE TABLE TAG
(
    ID   INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME TEXT UNIQUE CHECK (NAME != '')
);

CREATE TABLE IMAGES_TAGS
(
    IMAGE_ID INT NOT NULL,
    TAG_ID   INT NOT NULL,
    PRIMARY KEY (IMAGE_ID, TAG_ID),

    CONSTRAINT FK_IMAGE
        FOREIGN KEY (IMAGE_ID)
            REFERENCES IMAGE (ID),

    CONSTRAINT FK_TAG
        FOREIGN KEY (TAG_ID)
            REFERENCES TAG (ID)
);

CREATE UNIQUE INDEX UNIQUE_TAG_NAME_INDEX ON TAG (NAME);
CREATE UNIQUE INDEX UNIQUE_AUTHOR_NAME_INDEX ON AUTHOR (AUTHOR_NAME);